name: docs_fpocketR

channels:
  - conda-forge
  - defaults

dependencies:
  - python
  - pip
  - myst-parser
  - sphinx-book-theme=1.1.0
  - pydata-sphinx-theme
  - sphinx-design
  - sphinx-copybutton
